### ISSUE TITLE
Laravel 9.x Compatibility

### ISSUE THREAD

**Issue by esbolice** [percymamedy/laravel-dev-booter#13]
when do you plan to update the package to support Laravel 9?

**Comment by percymamedy** [comment]
Sorry about seeing this a bit late. I was a bit busy with other stuff and didn't have time to update to L9.
You are welcome to make a PR and I will get it merged in and release an L9 compatible version

**Comment by percymamedy** [comment]
https://github.com/percymamedy/laravel-dev-booter/pull/15
